### ISSUE TITLE
bluc_capi, ff, win: isActive() volta false

### ISSUE THREAD

**Issue by crivano** [bluecrystalsign/bluecrystal-signer#2]
getMsg() retornou "bluecrystal/applet/capi/iSignCapi"

**Comment by bluecrystalsign** [comment]
Funciona em outro navegador?

**Comment by crivano** [comment]
No IE estava dando erro de certificado revogado, portanto nem chegava nesse teste.

**Comment by bluecrystalsign** [comment]
E no Chrome?

**Comment by crivano** [comment]
Meu Chrome, tanto Win quanto Mac bloqueia os applets. Tem alguma configuração para ele aceitar applets?

**Comment by crivano** [comment]
Nova versão (que foi enviada por email) não resolveu o problema. O erro continua o mesmo.

**Comment by crivano** [comment]
O mesmo erro ocorre no IE.

**Comment by crivano** [comment]
Não havia instalado o runtime do VC++. Reiniciando a máquina...

**Comment by crivano** [comment]
Instalei o runtime 64, já que é um Win7 64bits, mas continua dando o mesmo erro. Será que instalo o 32bits?

```
Plug-in 10.65.2.19 do Java
Usando a versão do JRE 1.7.0_65-b19 Java HotSpot(TM) Client VM
Diretório home do usuário = C:\Users\tah
----------------------------------------------------
c:   limpar janela da console
f:   concluir objetos da fila de finalização
g:   coleta de lixo
h:   exibir esta mensagem de ajuda
l:   descartar lista de carregadores de classes
m:   imprimir uso de memória
o:   log do trigger
q:   ocultar console
r:   recarregar configuração da política
s:   descartar propriedades do sistema e de implantação
t:   descartar lista de threads
v:   descartar pilha de threads
x:   limpar cache do carregador de classes
0-5: definir nível de rastreamento como <n>
----------------------------------------------------
basic: Iniciando shutdown do applet
basic: Finalizado o shutdown do applet
basic: PluginMain.unregisterApplet: 6 from mananger sun.plugin2.applet.Applet2Manager@5c2dd1
basic: Listener de progresso removido: sun.plugin.util.ProgressMonitorAdapter@174acff
basic: Iniciando shutdown do applet
basic: Finalizado o shutdown do applet
basic: Listener de progresso removido: sun.plugin.util.ProgressMonitorAdapter@f8c04e
basic: PluginMain.unregisterApplet: 5 from mananger sun.plugin2.applet.Applet2Manager@1e44bf8
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at java.util.concurrent.CountDownLatch.await(Unknown Source)
	at bluecrystal.applet.sign.MySynch.await(MySynch.java:36)
	at bluecrystal.applet.sign.SignApplet$1.run(SignApplet.java:202)
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at java.util.concurrent.CountDownLatch.await(Unknown Source)
	at bluecrystal.applet.sign.MySynch.SKeyAwait(MySynch.java:79)
	at bluecrystal.applet.sign.SignApplet$2.run(SignApplet.java:223)
SKeyEndedCountDown: 1
SKeyReset
1
0
SKeyAwait: 1
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at java.util.concurrent.CountDownLatch.await(Unknown Source)
	at bluecrystal.applet.sign.MySynch.awaitLC(MySynch.java:57)
	at bluecrystal.applet.sign.SignApplet$3.run(SignApplet.java:242)
basic: Listener de progresso adicionado: sun.plugin.util.ProgressMonitorAdapter@6358de
security: Expected Main URL: http://localhost:8080/sigacd/bluc_p11.jar
basic: Listener de progresso adicionado: sun.plugin.util.ProgressMonitorAdapter@1242ed6
security: Expected Main URL: http://localhost:8080/sigacd/bluc_capi.jar
basic: Plugin2ClassLoader.addURL parent called for http://localhost:8080/sigacd/bluc_p11.jar
basic: Plugin2ClassLoader.addURL parent called for http://localhost:8080/sigacd/bluc_capi.jar
basic: Plugin2ClassLoader.addURL parent called for http://localhost:8080/sigacd/jna-platform-4.1.0.jar
basic: Plugin2ClassLoader.addURL parent called for http://localhost:8080/sigacd/jna-4.1.0.jar
security: Validar a cadeia de certificados usando a API CertPath
security: SSV validation:
    running: 1.7.0_65
    requested: null
    range: null
    javaVersionParam: null
    Rule Set version: null
network: Created version ID: 1.7.0.65
network: Created version ID: 1.7.0.65
security: continue with running version
security: Validar a cadeia de certificados usando a API CertPath
network: Created version ID: 1.7.0.65
network: Created version ID: 1.7
network: Created version ID: 2.2.65
basic: Applet carregado.
basic: Applet redimensionado e adicionado ao container pai
basic: PERF: AppletExecutionRunnable - applet.init() BEGIN ; jvmLaunch dt 1175489 us, pluginInit dt 157160443 us, TotalTime: 158335932 us
security: SSV validation:
    running: 1.7.0_65
    requested: null
    range: null
    javaVersionParam: null
    Rule Set version: null
network: Created version ID: 1.7.0.65
network: Created version ID: 1.7.0.65
security: continue with running version
network: Created version ID: 1.7.0.65
network: Created version ID: 1.7
cache: registerReference: com.sun.deploy.cache.MemoryCache$CachedResourceReference@bfac8f53: 4
network: Created version ID: 2.2.65
basic: Applet carregado.
basic: Applet redimensionado e adicionado ao container pai
basic: PERF: AppletExecutionRunnable - applet.init() BEGIN ; jvmLaunch dt 1175489 us, pluginInit dt 157164317 us, TotalTime: 158339806 us
basic: Applet inicializado
basic: Iniciando applet
basic: rollup de desempenho concluído
basic: Applet tornado visível
basic: Applet iniciado
basic: Clientes informados de que o applet foi iniciado
SKeyAwait: 1
Carregando (64 bits): C:\Users\tah\AppData\Local\Temp\signerCapi4621212806571640409.dll
Problemas carregando (64 bits) bluecrystal/applet/capi/iSignCapi
cache: registerReference: com.sun.deploy.cache.MemoryCache$CachedResourceReference@bfac8f53: 5
Carregando (32 bits): C:\Users\tah\AppData\Local\Temp\signerCapi6191675504309645518.dll
java.lang.NoClassDefFoundError: bluecrystal/applet/capi/iSignCapi
	at bluecrystal.applet.capi.LoaderUtil.loadNative(LoaderUtil.java:72)
	at bluecrystal.applet.capi.CapiSignService.loadDll(CapiSignService.java:144)
	at bluecrystal.applet.capi.CapiSignService.init(CapiSignService.java:42)
	at bluecrystal.applet.capi.SignApplet.init(SignApplet.java:67)
	at com.sun.deploy.uitoolkit.impl.awt.AWTAppletAdapter.init(Unknown Source)
	at sun.plugin2.applet.Plugin2Manager$AppletExecutionRunnable.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
basic: Applet inicializado
basic: Iniciando applet
basic: rollup de desempenho concluído
basic: Applet tornado visível
basic: Applet iniciado
basic: Clientes informados de que o applet foi iniciado
cache: Clean up the reference queue: http://localhost:8080/sigacd/bluc_capi.jar
cache: deregisterReference: com.sun.deploy.cache.MemoryCache$CachedResourceReference@bfac8f53: 4
cache: Clean up the reference queue: http://localhost:8080/sigacd/bluc_capi.jar
cache: deregisterReference: com.sun.deploy.cache.MemoryCache$CachedResourceReference@bfac8f53: 3
cache: Clean up the reference queue: http://localhost:8080/sigacd/bluc_capi.jar
cache: deregisterReference: com.sun.deploy.cache.MemoryCache$CachedResourceReference@bfac8f53: 2
```

**Comment by crivano** [comment]
Instalei o runtime 32bits e nada...

**Comment by crivano** [comment]
A P11 carrega bem, mas a CAPI não vai de jeito nenhum...
