### ISSUE TITLE
bluc_p11, ie, win: a assinatura PKCS7 está vindo sem nenhum certificado

### ISSUE THREAD

**Issue by crivano** [bluecrystalsign/bluecrystal-signer#7]
```
13:00:04,519 ERROR [org.jboss.as.webservices.invocation.InvocationHandlerJAXWS] (http-localhost/127.0.0.1:8080-9) JBAS015594: A invocação do método falhou com a exceção: null: java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:834) [rt.jar:1.7.0_71]
	at br.gov.jfrj.siga.cd.AssinaturaDigital.validarAssinaturaPKCS7(AssinaturaDigital.java:846) [siga-cd-1.2-SNAPSHOT.jar:]
```

A linha 846 é a última desse trecho:
```
		while (it.hasNext()) {
			SignerInformation signer = it.next();
			Collection<X509CertificateHolder> certCollection = certs.getMatches(signer.getSID());

			@SuppressWarnings("unused")
			String ss = signer.getDigestAlgOID();
			@SuppressWarnings("unused")
			String sss = signer.getDigestAlgorithmID().getObjectId().getId();

			Iterator<X509CertificateHolder> certIt = certCollection.iterator();
			X509CertificateHolder certHolder = certIt.next();
```

**Comment by crivano** [comment]
Rodando no meu Mac, a assinatura produzido pelo P11 passou pela validação do próprio BluC.
